### ISSUE TITLE
EET compatible dialogues?

### ISSUE THREAD

**Issue by RoxanneSHS** [Skitia/Recorder-BG1#2]
Are there plans to make the banter dialogues EET compatible?
Like in all other of your BG1 mods, the B-files used for vanilla NPCs are the BG2 files. Not a big issue, since the mods still install on EET and the banters trigger, they just break off after the opening line because the partner does not have the answer in its file.

**Comment by Skitia** [comment]
Yes. I finally figured out how it works and have it set up locally, in my next update I'll have the banters updated to be EET compatible.

**Comment by Skitia** [comment]
This is fixed as of this update.
